### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by EugenMayer** [refaktory/terraform-provider-minio#4]
Thanks for putting your time into such a well documented provider.

Still, is this project maintained? It seems like e.g. the current minio release would not work, when looking at the docker-compose.yml you test with. It's only 1 disk and now etcd, this should block quiet some APIs?

Using your version, I cannot get the provider up and running, getting connection refused all the time. Using the console port, using localhost:9000 my self here too(non SSL), also using the user created by 

```
    MINIO_ROOT_USER:
    MINIO_ROOT_PASSWORD:
```

Tried it with your `minio/minio:RELEASE.2021-08-20T18-32-01Z` and the current `minio/minio:RELEASE.2021-11-24T23-19-33Z
`

Thanks!

**Comment by EugenMayer** [comment]
Just in case this is important, i can automate user/policy/bucket creation using the `minio cli` without any issues (which I assume is using the same REST based API)

**Comment by EugenMayer** [comment]
In addition, it seem to be possible to configure policies/users/buckets without running with >= 4 disks / distributed mode when running it with `mc cli`

**Comment by rossigee** [comment]
Conclusion: No longer maintained.
